### ISSUE TITLE
Does this works with Tmux?

### ISSUE THREAD

**Issue by chris-fa** [Turbo87/webpack-notifier#33]
I'm running my webpack inside tmux. I don't see notifications

**Comment by Turbo87** [comment]
I don't see how tmux would be related to this. In any case this would be an issue of the underlying notification library. Can you move the issue there?

**Comment by gerges** [comment]
This project actually doesn't support `tmux` by default on `OSX` and will cause hung builds in that case. It's caused by a known limitation node-notifier: https://github.com/mikaelbr/node-notifier#use-inside-tmux-session. Unsure if it's possible to detect tmux from node. It might be worth echoing that limitation in your README as well.
