### ISSUE TITLE
Option to only notify when "status" has changed

### ISSUE THREAD

**Issue by CombeeMike** [Turbo87/webpack-notifier#43]
Since I have my editor set to `auto save after x sec` I'm getting many error notifications during typing.

Therefore I'd love to see an option to only get notified when the status changes (e.g. from `success` --> `error` or the other way around) but not for subsequent errors.

**Comment by Gvozd** [comment]
@CombeeMike 
It seems to me that this option will be inconvenient.

For example:
1.you write code, and you get an error because you haven't finished
2.you are done writing the code, fixing temporary errors
But at the same time, you still have one uncorrectable error that is not related to auto-saving and intermediate state of the code.

With this option, you will not be notified that you still have one more error, although I would like to draw attention to it (as opposed to intermediate ones)
